### ISSUE TITLE
Exercise 2 solution Makefile issue

### ISSUE THREAD

**Issue by slyt3** [learning-go-book-2e/ch1#1]
Code wont compile in the bash its will stop after build because its `.DEFAULT_GOAL` is `build`

You need to change `.DEFAULT_GOAL` to `clean`
And execute `clean: build` that clean would be the last who would be executed in the order

**Comment by kevslinger** [comment]
I think you are a little confused. The exercise asks to add a Makefile target to remove the files created by a go build. The exercise does not ask to add a Makefile target that builds the project and then removes the files created. In general, it doesn't really make sense to run build immediately before clean unless your goal is to build your project without keeping the artifacts of said build
